### ISSUE TITLE
Nothing found on Galaxy Alpha

### ISSUE THREAD

**Issue by passsy** [andriydruk/BonjourBrowser#1]
I tested your library on a wide range of devices and compared the results with https://play.google.com/store/apps/details?id=com.grokkt.android.bonjour

Only a crappy Samsung Galaxy Alpha with Android 4.4.2 did not show anything while at the same time the other app shows everything just fine. I got the following exception:

```
03-15 19:06:06.335 D/dalvikvm: Trying to load lib /data/app-lib/com.druk.bonjour.browser-1/libjdns_sd.so 0x42d7a7f0
03-15 19:06:06.345 D/dalvikvm: Added shared lib /data/app-lib/com.druk.bonjour.browser-1/libjdns_sd.so 0x42d7a7f0
03-15 19:06:06.345 D/dalvikvm: No JNI_OnLoad found in /data/app-lib/com.druk.bonjour.browser-1/libjdns_sd.so 0x42d7a7f0, skipping init
E/DNSSD: Error: 
                            com.apple.dnssd.AppleDNSSDException: DNS-SD Error -65563: SERVICENOTRUNNING
                                at com.apple.dnssd.AppleService.ThrowOnErr(DNSSD.java:652)
                                at com.apple.dnssd.AppleBrowser.<init>(DNSSD.java:704)
                                at com.apple.dnssd.AppleDNSSD._makeBrowser(DNSSD.java:557)
                                at com.apple.dnssd.DNSSD.browse(DNSSD.java:120)
                                at com.github.druk.rxdnssd.RxDnssd$1.getService(RxDnssd.java:72)
                                at com.github.druk.rxdnssd.RxDnssd$DNSSDServiceAction.call(RxDnssd.java:230)
                                at com.github.druk.rxdnssd.RxDnssd$DNSSDServiceAction.call(RxDnssd.java:216)
                                at rx.Observable$2.call(Observable.java:162)
                                at rx.Observable$2.call(Observable.java:154)
                                at rx.Observable.subscribe(Observable.java:8191)
                                at rx.Observable.subscribe(Observable.java:8158)
                                at rx.Observable.subscribe(Observable.java:7962)
                                at com.druk.bonjour.browser.ui.fragment.RegTypeBrowserFragment.startDiscovery(RegTypeBrowserFragment.java:74)
                                at com.druk.bonjour.browser.ui.fragment.ServiceBrowserFragment.onResume(ServiceBrowserFragment.java:126)
                                at android.support.v4.app.Fragment.performResume(Fragment.java:2020)
                                at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1107)
                                at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1252)
                                at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1234)
                                at android.support.v4.app.FragmentManagerImpl.dispatchResume(FragmentManager.java:2056)
                                at android.support.v4.app.FragmentController.dispatchResume(FragmentController.java:196)
                                at android.support.v4.app.FragmentActivity.onResumeFragments(FragmentActivity.java:505)
                                at android.support.v4.app.FragmentActivity.onPostResume(FragmentActivity.java:494)
                                at android.support.v7.app.AppCompatActivity.onPostResume(AppCompatActivity.java:161)
                                at android.app.Activity.performResume(Activity.java:5481)
                                at android.app.ActivityThread.performResumeActivity(ActivityThread.java:2906)
                                at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:2945)
                                at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2355)
                                at android.app.ActivityThread.access$800(ActivityThread.java:163)
                                at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1257)
                                at android.os.Handler.dispatchMessage(Handler.java:102)
                                at android.os.Looper.loop(Looper.java:157)
                                at android.app.ActivityThread.main(ActivityThread.java:5335)
                                at java.lang.reflect.Method.invokeNative(Native Method)
                                at java.lang.reflect.Method.invoke(Method.java:515)
                                at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1265)
                                at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1081)
                                at dalvik.system.NativeStart.main(Native Method)
```

I'm pretty sure I did nothing wrong using your library because this app here has the same problem. I hope you have an idea what could be wrong.

**Comment by passsy** [comment]
Found the same problem on a Samsung Galaxy Note 3 with Android 4.4.2 :(

**Comment by passsy** [comment]
```
03-15 19:32:26.675 I/knox: type=1400 msg=audit(1458066743.665:412): avc:  denied  { connectto } for  pid=32409 comm="bonjour.browser" path="/dev/socket/mdnsd" scontext=u:r:untrusted_app:s0 tcontext=u:r:mdnsd:s0 tclass=unix_stream_socket SEPF_SM-N9005_4.4.2_0046
```

maybe it has to do with knox

**Comment by andriydruk** [comment]
This exception means that your device doesn't contain started DNS-SD daemon. I heard about this problem on Samsung's 4.4.2 devices. In my opinion, it's vendor's "optimisation" for battery saving.
mDnsResponder provide two architecture type: with one system daemon or with embedded DNS-SD. To avoid issues like this developers should use embedded version ([Application that you mention above](https://play.google.com/store/apps/details?id=com.grokkt.android.bonjour) uses exactly this approach). 
Personally, I prefer "daemon way" because my app tries to be a good citizen in Android OS and uses system approach instead of running own DNS-SD.
To fix this issue I will create another flavor for devices API < 16 or Samsungs :) I've just started work on embedded version of RxDNSSD [here](https://github.com/andriydruk/RxDNSSD/tree/embedded)

**Comment by passsy** [comment]
I wouldn't bind the use of the embedded DNS-SD to the api level or the vendor. I would prefer if the lib itself listens to the `SERVICENOTRUNNING` error and automatically starts the embedded DNS-SD.

**Comment by funtax** [comment]
Hey Andrew, thanks for your work on the embedded version.
I see that you just implemented the vendor-specific switch but would also prefer the SERVICENOTRUNNING-variant.

Is your plan to implement this version, or do you stay on the vendor-switch?

Thanks again and in advance, great work!

**Comment by andriydruk** [comment]
Hi Martin and Pascal,

I'm planning to stay on "vendor-switch" variant. Of cause, your "SERVICENOTRUNNING-variant" would be preferable, but I assume that it's really hard to implement. First of all, neither Dalvik nor ART doesn't provide an official way to unload .so library from JVM process. The only way to do it's [dlclose()](http://pubs.opengroup.org/onlinepubs/7908799/xsh/dlclose.html), but it still can be very dangerous to hot-swap native implementations. 

In theory, it's possible but I suppose that it's out of the scope of my small open-source project, sorry.

In my Bonjour Browser I show a special error message and I'm asking users to send a report if SERVICENOTRUNNING happened. 

Thanks for your feedback.

**Comment by funtax** [comment]
Hey Andriy,

thanks for the details - I fully respect your decision.
I will have a look into your library and maybe replace the embedded version
inside "AirAudio" in the near future with your nice library.

Thanks for your efforts!

2016-04-14 22:17 GMT+02:00 Andriy Druk <notifications@github.com>:

**Comment by funtax** [comment]
Oh, maybe another workaround: Could we check if the mdns-deamon-process is
running after calling the DNSSD-service, and use the embedded version
otherwise?
Don't know, just a quick thought :)

2016-04-14 22:58 GMT+02:00 Martin Lehmann <info@issend.de>:

**Comment by andriydruk** [comment]
It's actual what I'm trying to do. The problem is that we should load native code to check if the daemon is running. And it makes impossible to load embedded version after that without crashes.

I assume that maybe it possible to check in some other way, without loading native libraries at all. Maybe [NsdManager](http://developer.android.com/reference/android/net/nsd/NsdManager.html) can help us. 

But the real problem is that I don't have access to  Samsung 4.4.2 devices and I use [Samsung's RTL](http://developer.samsung.com/remotetestlab/rtlDeviceList.action). Maybe, some day I'll face with such device and I'll investigate this problem more deeply.
