### ISSUE TITLE
app crashes silently due to StrictMode policy violation

### ISSUE THREAD

**Issue by barchandune** [andriydruk/BonjourBrowser#8]
```
03-22 13:51:44.325 30293 30293 D StrictMode: StrictMode policy violation; ~duration=180 ms: android.os.StrictMode$StrictModeDiskReadViolation: policy=23 violation=2
03-22 13:51:44.325 30293 30293 D StrictMode: 	at android.os.StrictMode$AndroidBlockGuardPolicy.onReadFromDisk(StrictMode.java:1137)
03-22 13:51:44.325 30293 30293 D StrictMode: 	at libcore.io.BlockGuardOs.open(BlockGuardOs.java:182)
03-22 13:51:44.325 30293 30293 D StrictMode: 	at libcore.io.IoUtils.canOpenReadOnly(IoUtils.java:165)
03-22 13:51:44.325 30293 30293 D StrictMode: 	at dalvik.system.DexPathList.findLibrary(DexPathList.java:383)
03-22 13:51:44.325 30293 30293 D StrictMode: 	at dalvik.system.BaseDexClassLoader.findLibrary(BaseDexClassLoader.java:77)
03-22 13:51:44.325 30293 30293 D StrictMode: 	at java.lang.Runtime.loadLibrary(Runtime.java:361)
03-22 13:51:44.325 30293 30293 D StrictMode: 	at java.lang.System.loadLibrary(System.java:988)
03-22 13:51:44.325 30293 30293 D StrictMode: 	at com.github.druk.dnssd.AppleDNSSD._init(InternalDNSSD.java:552)
03-22 13:51:44.325 30293 30293 D StrictMode: 	at com.github.druk.dnssd.InternalDNSSD.init(InternalDNSSD.java:91)
03-22 13:51:44.325 30293 30293 D StrictMode: 	at com.github.druk.dnssd.DNSSD.<init>(DNSSD.java:79)
03-22 13:51:44.325 30293 30293 D StrictMode: 	at com.github.druk.dnssd.DNSSD.<init>(DNSSD.java:75)
03-22 13:51:44.325 30293 30293 D StrictMode: 	at com.github.druk.dnssd.DNSSDBindable.<init>(DNSSDBindable.java:32)
03-22 13:51:44.325 30293 30293 D StrictMode: 	at com.github.druk.rxdnssd.RxDnssdBindable.<init>(RxDnssdBindable.java:32)
03-22 13:51:44.325 30293 30293 D StrictMode: 	at com.druk.servicebrowser.BonjourApplication.createDnssd(BonjourApplication.java:100)
03-22 13:51:44.325 30293 30293 D StrictMode: 	at com.druk.servicebrowser.BonjourApplication.onCreate(BonjourApplication.java:59)
```

**Comment by andriydruk** [comment]
It's penalty log, not a crash
Please, try to find real crash log in logcat
